### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [marmistrz/QDict#2]
You can add Screenshots for F-Droid, too, if you want.
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/
https://gitlab.com/snippets/1895688
That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane. This is just one way that you can also add screenshots to the app view if you can. If you added screenshots (then F-Droid is happy) and if you can't add any -> then you can close the issue because it was only an info. Thank you that your app is available in
fdroid. Very much for your attention.

it is only information.

**Comment by marmistrz** [comment]
I used the screenshots that upstream used for Google Play upload. Do I need to do anything extra for F-Droid to pick up the new metadata?

**Comment by marmistrz** [comment]
Closing this issue. Apparently the only way to have these changes picked up is to do a new release [1], which I won't do until there are any changes in the app itself. 

[1] https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7004#note_575968727
