### ISSUE TITLE
Some display issues on several pages

### ISSUE THREAD

**Issue by EasyVector** [marmistrz/QDict#5]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figures below, **there are several display glitches**: 

**1. On the about page, the version string is totally blocked by the border around it.
2. On the recent page, the string of "Recent Words" overlaps the string of "0 keywords" after.
3. On the side navigator, if the "Select dictionary" is triggered, the text on the new "Select dictionary" page could not be seen fully.**

Those may be adaptation problems. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 2.1.3, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see all of the texts on those pages without been blocked or overlapping.

**Steps to reproduce the behavior:**

1. use the largest font and display in the display setting
2. open this app, click the three dashes at the top-left of the main page to trigger the side navigator
3. click the "Select dictionary" button on the side navigator
4. an error could be seen
5. go back, trigger the "about" button
6. another error could be seen
7. go back, trigger the "Recent Words" button
8. another error could be seen

**Screenshots**

(The overlapped part and the blocked part have been circled in red rectangles)

<img src="https://user-images.githubusercontent.com/25502419/131220584-2bb43537-9825-4663-9e33-06aedd77e5fa.png" alt="copy" width="250"/> <img src="https://user-images.githubusercontent.com/25502419/131220585-c3490844-8ff3-4367-9d2b-3147758f4b56.png" alt="copy" width="250"/> <img src="https://user-images.githubusercontent.com/25502419/131220587-0e8269f9-1cee-4220-b4c5-666ed880bf3c.png" alt="copy" width="250"/>

**Environment**

1. Version of QDict: 2.1.3
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by marmistrz** [comment]
Thanks a lot for the screenshots and the PR!

**Comment by marmistrz** [comment]
Fixed by #10.
